### ISSUE TITLE
Migrating to AndroidX from support lib

### ISSUE THREAD

**Issue by udhay24** [opendatakit/skunkworks-bat#12]
@jbeorse can we migrate to androidX since android support lib is deprecated, as the android documentation says

> You can continue to use the support library. Historical artifacts (those versioned 27 and earlier, and packaged as android.support.*) will remain available on Google Maven. However, all new library development will occur in the AndroidX library. 

> We recommend using the AndroidX libraries in all new projects. You should also consider migrating existing projects to AndroidX as well.

**Comment by jbeorse** [comment]
Can we do this while maintaining a minSDK of 17? If so, then yes, I am in support of this. But maintaining this minSDK is a hard requirement.

**Comment by wbrunette** [comment]
@linl33 since you help us keep the rest of the tool suite together in compatibility please comment.

**Comment by udhay24** [comment]
@jbeorse yes the minimum sdk  can be maintained. but have to change the compiletime sdk to 28 and gradle to 3.3.2. is it ok?

**Comment by linl33** [comment]
I have 1 question about the transition process. 

This project depends on 2 of our libraries: androidlibrary and androidcommon. Right now, we depend on the aar of those projects, which the AndroidX jetifier could handle. However, this project will eventually have to support including those 2 libraries as both as a project dependency and as a binary dependency. Is it going to be a problem if we don't migrate those libraries?

**Comment by udhay24** [comment]
I am sorry.i don't know about it.

**Comment by linl33** [comment]
Fixed in opendatakit/skunkworks-bat#14
