### ISSUE TITLE
Add ODK 2.1 support

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/skunkworks-bat#7]
AIDL names should be updated to match the new ODK 2.1 API

**Comment by DreamyPhobic** [comment]
Please give some detail about this, I think the error discussed in #9 is due to mismatch of AIDL names in server and client side.

**Comment by linl33** [comment]
Some services provided by ODK Services changed names from 2.0 -> 2.1. Some code changes in `bat` might be necessary to make it compatible with 2.1. But it might suffice to just update the 2 libraries: `androidcommon` and `androidlibrary` to the latest version.
