### ISSUE TITLE
Add permissions requests

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/skunkworks-bat#8]
Currently the user must open Services first to grant permissions. This app should handle its permissions requests.

**Comment by tavishjain** [comment]
Can I work on the issue ?

**Comment by linl33** [comment]
Hi, 

Please go ahead and work on this. You can look at [Tables](https://github.com/opendatakit/tables) or [Survey](https://github.com/opendatakit/survey) to see how they implemented this feature. 

If you need help, please come to the ODK Slack, channel \#internships.

**Comment by thesherrinford** [comment]
I've added an internet request and camera request.
Do we need to add more requests?

**Comment by Milindmtg** [comment]
Sir,Can I work on this issue

**Comment by linl33** [comment]
Hi @Milindmtg, 

This issue has already been claimed. Please find another issue on this repo, [skunkworks-parrot](https://github.com/opendatakit/skunkworks-parrot), or [here](https://github.com/opendatakit/opendatakit/issues). 

<br>

@tavishjain can you give us an update on your progress?

**Comment by Saikat2019** [comment]
is anyone working on this ?

**Comment by DreamyPhobic** [comment]
It's been a long time, no one has responded, so I am claiming this issue. Thank You.
